const courseData = {
  '民法': {
    phases: {
      '专题强化': {
        teacher: '【民法】',
        bvid: 'BV11zs1zSEPS',
        status: 'complete',
        episodes: [
          { idx: 1, title: '专题一 民法基本原则', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=1' },
          { idx: 2, title: '专题二_民事权利及其私力保护', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=2' },
          { idx: 3, title: '专题三 民事权利能力、民事行为能力与自然人的监护', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=3' },
          { idx: 4, title: '专题四 宣告失踪、宣告死亡', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=4' },
          { idx: 5, title: '专题五 法人', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=5' },
          { idx: 6, title: '专题六 意思表示、实践行为与要式行为', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=6' },
          { idx: 7, title: '专题七 民事法律行为的有效、生效与效力瑕疵', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=7' },
          { idx: 8, title: '专题八 代理', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=8' },
          { idx: 9, title: '专题九 诉讼时效', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=9' },
          { idx: 10, title: '专题十 无因管理', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=10' },
          { idx: 11, title: '专题十一 不当得利', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=11' },
          { idx: 12, title: '专题十二 物权概述、公示原则与公示方法', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=12' },
          { idx: 13, title: '专题十三 非基于合同引起的物权变动、异议登记、预告登记', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=13' },
          { idx: 14, title: '专题十四 不动产所有权', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=14' },
          { idx: 15, title: '专题十五 所有权的原始取得之一：善意取得', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=15' },
          { idx: 16, title: '专题十六 所有权的原始取得之二：先占与添附', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=16' },
          { idx: 17, title: '专题十七 共有', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=17' },
          { idx: 18, title: '专题十八土地承包经营权、建设用地使用权与宅基地使用权+专题十九 居住权与地役权', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=18' },
          { idx: 19, title: '专题二十 占有概述', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=19' },
          { idx: 20, title: '专题二十一 无权占有的返还', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=20' },
          { idx: 21, title: '专题二十二 债的分类', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=21' },
          { idx: 22, title: '专题二十三 债的转移', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=22' },
          { idx: 23, title: '专题二十四 债的保全', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=23' },
          { idx: 24, title: '专题二十五 债的消灭', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=24' },
          { idx: 25, title: '专题二十六 合同概述', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=25' },
          { idx: 26, title: '专题二十七 合同的订立', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=26' },
          { idx: 27, title: '专题二十八 合同的履行', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=27' },
          { idx: 28, title: '专题二十九 合同的解除', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=28' },
          { idx: 29, title: '专题三十 缔约过失责任', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=29' },
          { idx: 30, title: '专题三十一 违约责任', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=30' },
          { idx: 31, title: '专题三十二 买卖合同之一：无权处分、多重买卖', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=31' },
          { idx: 32, title: '专题三十三 买卖合同之二：买卖物', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=32' },
          { idx: 33, title: '专题三十四 买卖合同之三：特种买卖', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=33' },
          { idx: 34, title: '专题三十五 赠与合同、民间借贷合同', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=34' },
          { idx: 35, title: '专题三十六 租赁合同、融资租赁合同', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=35' },
          { idx: 36, title: '专题三十七 保理合同', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=36' },
          { idx: 37, title: '专题三十八_承揽合同、建设工程合同', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=37' },
          { idx: 38, title: '专题三十九 运输合同、技术合同', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=38' },
          { idx: 39, title: '专题四十_保管合同、仓储合同__专题四十一_委托合同、行纪合同、中介合同', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=39' },
          { idx: 40, title: '专题四十二 物业服务合同、合伙合同', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=40' },
          { idx: 41, title: '专题四十三_担保合同与担保责任（上）', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=41' },
          { idx: 42, title: '专题四十三_担保合同与担保责任（下）', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=42' },
          { idx: 43, title: '专题四十四 共同担保', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=43' },
          { idx: 44, title: '专题四十五 担保物权的一般原理', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=44' },
          { idx: 45, title: '专题四十六_抵押权（上）', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=45' },
          { idx: 46, title: '专题四十六_抵押权（下）', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=46' },
          { idx: 47, title: '专题四十七 质权', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=47' },
          { idx: 48, title: '专题四十八 留置权', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=48' },
          { idx: 49, title: '专题四十九 担保物权竞存', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=49' },
          { idx: 50, title: '专题五十 保证', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=50' },
          { idx: 51, title: '专题五十一 定金', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=51' },
          { idx: 52, title: '专题五十二 人格支配', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=52' },
          { idx: 53, title: '专题五十三 人格保护', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=53' },
          { idx: 54, title: '专题五十四 侵权责任概述', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=54' },
          { idx: 55, title: '专题五十五 侵权损害赔偿责任的承担', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=55' },
          { idx: 56, title: '专题五十六 共同侵权与行为结合', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=56' },
          { idx: 57, title: '专题五十七 特别侵权', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=57' },
          { idx: 58, title: '专题五十八  亲属关系与结婚', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=58' },
          { idx: 59, title: '专题五十九 夫妻财产关系', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=59' },
          { idx: 60, title: '专题六十 离婚', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=60' },
          { idx: 61, title: '专题六十一 收养法', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=61' },
          { idx: 62, title: '专题六十二 继承法', link: 'https://www.bilibili.com/video/BV11zs1zSEPS?p=62' }
        ]
      },
      '真题破译': {
        teacher: '已完结',
        bvid: 'BV1m7XZBrE4Q',
        status: 'complete',
        episodes: [
          { idx: 1, title: '第一讲 民法的基本原则、民事法律关系和民事权利 （1题-17题）', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=1' },
          { idx: 2, title: '第二讲 民事主体 （18题-46题）', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=2' },
          { idx: 3, title: '第三讲 民事法律行为 （47题-77题）', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=3' },
          { idx: 4, title: '第四讲 代理与诉讼时效 （78题-97题）', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=4' },
          { idx: 5, title: '第五讲 无因管理与不当得利 (98题-110题）', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=5' },
          { idx: 6, title: '第六讲 物权法总论 (111题-128题)', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=6' },
          { idx: 7, title: '第七讲 所有权 (129题-152题)', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=7' },
          { idx: 8, title: '第八讲 用益物权 (153题-161题)', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=8' },
          { idx: 9, title: '第九讲 占有 (162题-174题)', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=9' },
          { idx: 10, title: '第十讲 债法总论 (175题-210题)', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=10' },
          { idx: 11, title: '第十一讲 合同法总论 (211题-266题)', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=11' },
          { idx: 12, title: '第十二讲 合同法分论（267题-331题）', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=12' },
          { idx: 13, title: '第十三讲 担保概述 （332题-339题）', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=13' },
          { idx: 14, title: '第十四讲 担保物权（340题-374题）', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=14' },
          { idx: 15, title: '第十五讲 担保债权（375题-382题）', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=15' },
          { idx: 16, title: '第十六讲 人格保护（383题-398题）', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=16' },
          { idx: 17, title: '第十七讲 侵权责任一般理论（399题-412题）', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=17' },
          { idx: 18, title: '第十八讲 共同侵权与特别侵权  (413题-451题）', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=18' },
          { idx: 19, title: '第十九讲 婚姻法（452题-472题）', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=19' },
          { idx: 20, title: '第二十讲 收养法（473题-476题）', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=20' },
          { idx: 21, title: '第二十一讲 继承法 （477题-497题）', link: 'https://www.bilibili.com/video/BV1m7XZBrE4Q?p=21' }
        ]
      }
    }
  },
  '刑法': {
    phases: {
      '专题强化': {
        teacher: '【刑法】',
        bvid: 'BV15kyBB5Eg8',
        status: 'complete',
        episodes: [
          { idx: 1, title: '专题1_刑法概说', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=1' },
          { idx: 2, title: '专题2_刑法的基本原则', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=2' },
          { idx: 3, title: '专题3_刑法的解释', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=3' },
          { idx: 4, title: '专题4_刑法的适用范围', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=4' },
          { idx: 5, title: '专题5_犯罪概说', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=5' },
          { idx: 6, title: '专题6_犯罪构成和构成要件', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=6' },
          { idx: 7, title: '专题7_行为主体', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=7' },
          { idx: 8, title: '专题8_危害行为', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=8' },
          { idx: 9, title: '专题9_行为对象、危害结果和行为状态', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=9' },
          { idx: 10, title: '专题10_因果关系', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=10' },
          { idx: 11, title: '专题11_故意', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=11' },
          { idx: 12, title: '专题12_过失', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=12' },
          { idx: 13, title: '专题13_事实上的认识错误', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=13' },
          { idx: 14, title: '专题14_特殊的主观要素', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=14' },
          { idx: 15, title: '专题15_正当防卫', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=15' },
          { idx: 16, title: '专题16_紧急避险', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=16' },
          { idx: 17, title: '专题17_其他违法阻却事由', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=17' },
          { idx: 18, title: '专题18_责任能力的阻却', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=18' },
          { idx: 19, title: '专题19_法律认识错误', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=19' },
          { idx: 20, title: '专题20_缺乏期待可能性', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=20' },
          { idx: 21, title: '专题21 未完成形态概述', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=21' },
          { idx: 22, title: '专题22 犯罪预备', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=22' },
          { idx: 23, title: '专题23 犯罪未遂', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=23' },
          { idx: 24, title: '专题24 犯罪中止', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=24' },
          { idx: 25, title: '专题25 共同犯罪的基本理论', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=25' },
          { idx: 26, title: '专题26 共同正犯', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=26' },
          { idx: 27, title: '专题27 间接正犯', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=27' },
          { idx: 28, title: '专题28 正犯与共犯', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=28' },
          { idx: 29, title: '专题29 共同犯罪人的责任', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=29' },
          { idx: 30, title: '专题30 特殊的共同犯罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=30' },
          { idx: 31, title: '专题31_共同犯罪的复杂问题', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=31' },
          { idx: 32, title: '专题32_罪数的基本原理', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=32' },
          { idx: 33, title: '专题33_实质的一罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=33' },
          { idx: 34, title: '专题34_法定的一罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=34' },
          { idx: 35, title: '专题35_处断的一罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=35' },
          { idx: 36, title: '专题36_法律和司法解释的特别规定', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=36' },
          { idx: 37, title: '专题37_主刑', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=37' },
          { idx: 38, title: '专题38_附加刑', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=38' },
          { idx: 39, title: '专题39_社区矫正', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=39' },
          { idx: 40, title: '专题40_非刑罚处罚方法', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=40' },
          { idx: 41, title: '专题41_量刑的原则和种类', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=41' },
          { idx: 42, title: '专题42_累犯', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=42' },
          { idx: 43, title: '专题43_自首、坦白、立功', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=43' },
          { idx: 44, title: '专题44_数罪并罚', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=44' },
          { idx: 45, title: '专题45_缓刑', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=45' },
          { idx: 46, title: '专题46_减刑', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=46' },
          { idx: 47, title: '专题47_假释', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=47' },
          { idx: 48, title: '专题48_追诉时效', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=48' },
          { idx: 49, title: '专题49_分则概说', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=49' },
          { idx: 50, title: '专题50_危害国家安全罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=50' },
          { idx: 51, title: '专题51_危险方法类犯罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=51' },
          { idx: 52, title: '专题52_破坏公用设施类犯罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=52' },
          { idx: 53, title: '专题53_恐怖活动犯罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=53' },
          { idx: 54, title: '专题54_枪支、弹药、爆炸物、危险物质罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=54' },
          { idx: 55, title: '专题55_事故犯罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=55' },
          { idx: 56, title: '专题56_生产、销售伪劣商品罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=56' },
          { idx: 57, title: '专题57_走私罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=57' },
          { idx: 58, title: '专题58_妨害对公司、企业的管理秩序罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=58' },
          { idx: 59, title: '专题59_货币犯罪和票证犯罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=59' },
          { idx: 60, title: '专题60_贷款犯罪和洗钱罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=60' },
          { idx: 61, title: '专题61_非法集资犯罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=61' },
          { idx: 62, title: '专题62_金融诈骗罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=62' },
          { idx: 63, title: '专题63_危害税收征管罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=63' },
          { idx: 64, title: '专题64_侵犯知识产权罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=64' },
          { idx: 65, title: '专题65_扰乱市场秩序罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=65' },
          { idx: 66, title: '专题66_侵犯生命、健康的犯罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=66' },
          { idx: 67, title: '专题67_侵犯性自治权的犯罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=67' },
          { idx: 68, title: '专题68 侵犯人身自由的犯罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=68' },
          { idx: 69, title: '专题69 侵犯婚姻家庭权利的犯罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=69' },
          { idx: 70, title: '专题70 侵犯名誉权、民主权利罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=70' },
          { idx: 71, title: '专题71 强制占有型的财产犯罪（上）', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=71' },
          { idx: 72, title: '专题71 强制占有型的财产犯罪（下）', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=72' },
          { idx: 73, title: '专题72 平和占有型的财产犯罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=73' },
          { idx: 74, title: '专题73 挪用占有型的财产犯罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=74' },
          { idx: 75, title: '专题74 破坏型的财产犯罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=75' },
          { idx: 76, title: '专题75 扰乱公共秩序罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=76' },
          { idx: 77, title: '专题76 妨害司法罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=77' },
          { idx: 78, title: '专题77 妨害国（边）境管理罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=78' },
          { idx: 79, title: '专题78 妨害文物管理罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=79' },
          { idx: 80, title: '专题79 危害公共卫生罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=80' },
          { idx: 81, title: '专题80  破坏环境资源保护罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=81' },
          { idx: 82, title: '专题81 走私、贩卖、运输、制造毒品罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=82' },
          { idx: 83, title: '专题82 组织、强迫、引诱、容留、介绍卖淫罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=83' },
          { idx: 84, title: '专题83 制作、贩卖传播淫秽物品罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=84' },
          { idx: 85, title: '专题84贪污犯罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=85' },
          { idx: 86, title: '专题85贿赂犯罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=86' },
          { idx: 87, title: '专题86滥用职权罪和玩忽职守罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=87' },
          { idx: 88, title: '专题87 其他渎职罪', link: 'https://www.bilibili.com/video/BV15kyBB5Eg8?p=88' }
        ]
      },
      '真题破译': {
        teacher: '更新中',
        bvid: 'BV185oTBLE23',
        status: 'complete',
        episodes: [
          { idx: 1, title: '第一讲（上） 刑法概说（1~10）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=1' },
          { idx: 2, title: '第一讲（下） 刑法概说（11~18）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=2' },
          { idx: 3, title: '第二讲 犯罪构成的概述（19）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=3' },
          { idx: 4, title: '第三讲（上） 构成要件符合性（20~37）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=4' },
          { idx: 5, title: '第三讲（中） 构成要件符合性（38~50）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=5' },
          { idx: 6, title: '第三讲（下） 构成要件符合性（51~66）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=6' },
          { idx: 7, title: '第四讲（上） 违法阻却事由（67~78）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=7' },
          { idx: 8, title: '第四讲（下） 违法阻却事由（79～91）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=8' },
          { idx: 9, title: '第五讲 （上）有责性（92～104）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=9' },
          { idx: 10, title: '第五讲（下）有责性（105～128）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=10' },
          { idx: 11, title: '第六讲（上） 故意犯罪形态（129～143）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=11' },
          { idx: 12, title: '第六讲（下） 故意犯罪形态（144～159）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=12' },
          { idx: 13, title: '第七讲（上）共同犯罪（160～176）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=13' },
          { idx: 14, title: '第七讲（下）共同犯罪（177～186）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=14' },
          { idx: 15, title: '第八讲 罪数（187～202）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=15' },
          { idx: 16, title: '第九讲   刑罚体系（203～212）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=16' },
          { idx: 17, title: '第十讲   刑罚的裁量（213～216）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=17' },
          { idx: 18, title: '第十一讲  刑罚的执行（217～233）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=18' },
          { idx: 19, title: '第十二讲  刑罚的消灭（234～238）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=19' },
          { idx: 20, title: '第十三讲（上）  侵犯公民人身权利、民主权利罪（239～257）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=20' },
          { idx: 21, title: '第十三讲（下）  侵犯公民人身权利、民主权利罪（258～268）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=21' },
          { idx: 22, title: '第十四讲（一）  侵犯财产罪（269～286）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=22' },
          { idx: 23, title: '第十四讲（二）  侵犯财产罪（287～298）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=23' },
          { idx: 24, title: '第十四讲（三）  侵犯财产罪（299～316）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=24' },
          { idx: 25, title: '第十四讲（四）  侵犯财产罪（317～336）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=25' },
          { idx: 26, title: '第十四讲（五）  侵犯财产罪（337~350）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=26' },
          { idx: 27, title: '第十四讲（六）  侵犯财产罪（351~362）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=27' },
          { idx: 28, title: '第十五讲（上） 危害公共安全罪（363~376）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=28' },
          { idx: 29, title: '第十五讲（下） 危害公共安全罪（377～391）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=29' },
          { idx: 30, title: '第十六讲 （上）破坏社会主义市场经济秩序罪（392～415）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=30' },
          { idx: 31, title: '第十六讲 （下）破坏社会主义市场经济秩序罪（416～435）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=31' },
          { idx: 32, title: '第十七讲（上） 妨害社会管理秩序罪（436～455）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=32' },
          { idx: 33, title: '第十七讲（中） 妨害社会管理秩序罪（456～471）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=33' },
          { idx: 34, title: '第十七讲（下） 妨害社会管理秩序罪（472～487）', link: 'https://www.bilibili.com/video/BV185oTBLE23?p=34' }
        ]
      }
    }
  },
  '刑诉法': {
    phases: {
      '专题强化': {
        teacher: '【刑诉法】',
        bvid: 'BV1vmkTBQELC',
        status: 'complete',
        episodes: [
          { idx: 1, title: '专题1 刑事诉讼法概说（上）', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=1' },
          { idx: 2, title: '专题1 刑事诉讼法概说（下）', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=2' },
          { idx: 3, title: '专题2 刑事诉讼的基本理念', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=3' },
          { idx: 4, title: '专题3 刑事诉讼的基本范畴', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=4' },
          { idx: 5, title: '专题4 基本原则概述', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=5' },
          { idx: 6, title: '专题5 基本原则内容（上）', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=6' },
          { idx: 7, title: '专题5 基本原则的内容(下）', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=7' },
          { idx: 8, title: '专题6 刑事诉讼中的专门机关', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=8' },
          { idx: 9, title: '专题7 当事人', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=9' },
          { idx: 10, title: '专题8 其他诉讼参与人', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=10' },
          { idx: 11, title: '专题9 立案管辖', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=11' },
          { idx: 12, title: '专题10 审判管辖', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=12' },
          { idx: 13, title: '专题11 特殊案件的管辖', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=13' },
          { idx: 14, title: '专题12 回避概述', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=14' },
          { idx: 15, title: '专题13 回避的程序', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=15' },
          { idx: 16, title: '专题14 辩护制度概述', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=16' },
          { idx: 17, title: '专题15 辩护制度的具体内容（上）', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=17' },
          { idx: 18, title: '专题15 辩护制度的具体内容（下）', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=18' },
          { idx: 19, title: '专题16 刑事代理制度', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=19' },
          { idx: 20, title: '专题17 刑事证据概述', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=20' },
          { idx: 21, title: '专题18 刑事证据的种类', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=21' },
          { idx: 22, title: '专题19 刑事证据的理论分类', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=22' },
          { idx: 23, title: '专题20 刑事证据规则', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=23' },
          { idx: 24, title: '专题21 刑事诉讼证明', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=24' },
          { idx: 25, title: '专题22 强制措施概述', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=25' },
          { idx: 26, title: '专题23 拘传', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=26' },
          { idx: 27, title: '专题24 取保候审', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=27' },
          { idx: 28, title: '专题25 监视居住', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=28' },
          { idx: 29, title: '专题26 拘留', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=29' },
          { idx: 30, title: '专题27 逮捕', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=30' },
          { idx: 31, title: '专题28 附带民事诉讼概述', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=31' },
          { idx: 32, title: '专题29 附带民事诉讼当事人', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=32' },
          { idx: 33, title: '专题30 附带民事诉讼的提起', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=33' },
          { idx: 34, title: '专题31 附带民事诉讼的审理程序', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=34' },
          { idx: 35, title: '专题32 期间', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=35' },
          { idx: 36, title: '专题33 送达', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=36' },
          { idx: 37, title: '专题34 立案概述', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=37' },
          { idx: 38, title: '专题35 立案程序与立案监督', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=38' },
          { idx: 39, title: '专题36 侦查概述', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=39' },
          { idx: 40, title: '专题37 侦查行为', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=40' },
          { idx: 41, title: '专题38 侦查终结、侦查羁押与补充侦查', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=41' },
          { idx: 42, title: '专题39 起诉概述', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=42' },
          { idx: 43, title: '专题40 提起公诉的程序', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=43' },
          { idx: 44, title: '专题41 提起自诉的程序', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=44' },
          { idx: 45, title: '专题42 刑事审判概说', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=45' },
          { idx: 46, title: '专题43 刑事审判的模式和原则', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=46' },
          { idx: 47, title: '专题44 刑事审判的基本制度', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=47' },
          { idx: 48, title: '专题45 公诉案件第一审程序 （上）', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=48' },
          { idx: 49, title: '专题45 公诉案件第一审程序(下)', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=49' },
          { idx: 50, title: '专题46 自诉案件第一审程序', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=50' },
          { idx: 51, title: '专题47 简易程序与速裁程序', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=51' },
          { idx: 52, title: '专题48 判决、裁定与决定', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=52' },
          { idx: 53, title: '专题49 二审程序的提起', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=53' },
          { idx: 54, title: '专题50 二审程序的审理（上）', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=54' },
          { idx: 55, title: '专题50 二审程序的审理（下）', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=55' },
          { idx: 56, title: '专题51 涉案财物的处理', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=56' },
          { idx: 57, title: '专题52 复核程序概述', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=57' },
          { idx: 58, title: '专题53 在法定刑以下判处刑罚的案件的核准程序', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=58' },
          { idx: 59, title: '专题54 死刑立即执行案件的复核程序', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=59' },
          { idx: 60, title: '专题55 死刑缓期二年执行案件的复核程序', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=60' },
          { idx: 61, title: '专题56 审判监督程序概述', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=61' },
          { idx: 62, title: '专题57 审判监督程序的提起', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=62' },
          { idx: 63, title: '专题58 依照审判监督程序对案件的重新审判', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=63' },
          { idx: 64, title: '专题59 执行概述', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=64' },
          { idx: 65, title: '专题60 各种判决、裁定的执行程序', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=65' },
          { idx: 66, title: '专题61 执行的变更程序', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=66' },
          { idx: 67, title: '专题62 未成年人刑事案件诉讼程序概述', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=67' },
          { idx: 68, title: '专题63 未成年人刑事案件诉讼程序的方针和原则', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=68' },
          { idx: 69, title: '专题64 未成年人刑事案件诉讼程序的具体规定', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=69' },
          { idx: 70, title: '专题65 刑事和解概述', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=70' },
          { idx: 71, title: '专题66 刑事和解诉讼程序的具体规定', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=71' },
          { idx: 72, title: '专题67 缺席审判程序概述', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=72' },
          { idx: 73, title: '专题68 缺席审判程序的具体规定', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=73' },
          { idx: 74, title: '专题69 犯罪嫌疑人、被告人逃匿、死亡案件违法所得没收程序概述', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=74' },
          { idx: 75, title: '专题70 犯罪嫌疑人、被告人逃匿、死亡案件违法所得没收程序的具体', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=75' },
          { idx: 76, title: '专题71 依法不负刑事责任的精神病人的强制医疗程序概述', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=76' },
          { idx: 77, title: '专题72 依法不负刑事责任的精神病人的强制医疗程序的具体规定', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=77' },
          { idx: 78, title: '专题73 涉外刑事诉讼程序', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=78' },
          { idx: 79, title: '专题74 刑事司法协助', link: 'https://www.bilibili.com/video/BV1vmkTBQELC?p=79' }
        ]
      },
      '真题破译': {
        teacher: '已完结',
        bvid: 'BV1eDXzBKEZ6',
        status: 'complete',
        episodes: [
          { idx: 1, title: '第一讲 刑事诉讼概述（1题-14题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=1' },
          { idx: 2, title: '第二讲 刑事诉讼法的基本原则（15题-33题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=2' },
          { idx: 3, title: '第三讲 刑事诉讼中的专门机关与参与人（34题-51题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=3' },
          { idx: 4, title: '第四讲 管辖（52题-72题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=4' },
          { idx: 5, title: '第五讲 回避（73题-76题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=5' },
          { idx: 6, title: '第六讲 辩护与代理（77题-93题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=6' },
          { idx: 7, title: '第七讲（上） 刑事证据（94题-100题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=7' },
          { idx: 8, title: '第七讲（中） 刑事证据(101题-114题)', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=8' },
          { idx: 9, title: '第七讲（下）刑事证据（115题-128题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=9' },
          { idx: 10, title: '第八讲 强制措施(129题-151题)', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=10' },
          { idx: 11, title: '第九讲 附带民事诉讼(152题-157题)', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=11' },
          { idx: 12, title: '第十讲 期间与送达(158题-161题)', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=12' },
          { idx: 13, title: '第十一讲 立案(162题-167题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=13' },
          { idx: 14, title: '第十二讲 侦查(168题-193题)', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=14' },
          { idx: 15, title: '第十三讲 起诉（194题-201题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=15' },
          { idx: 16, title: '第十四讲 刑事审判概述（202题-213题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=16' },
          { idx: 17, title: '第十五讲（上） 第一审程序（214题-231题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=17' },
          { idx: 18, title: '第十五讲（下） 第一审程序（232题-249题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=18' },
          { idx: 19, title: '第十六讲 第二审程序（250题-264题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=19' },
          { idx: 20, title: '第十七讲 死刑复核程序（265题-269题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=20' },
          { idx: 21, title: '第十八讲 审判监督程序（270题-277题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=21' },
          { idx: 22, title: '第十九讲 执行（278题-291题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=22' },
          { idx: 23, title: '第二十讲 未成年人刑事案件诉讼程序（292题-307题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=23' },
          { idx: 24, title: '第二十一讲 当事人和解的公诉案件诉讼程序（308题-315题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=24' },
          { idx: 25, title: '第二十二讲 缺席审判程序（316题-319题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=25' },
          { idx: 26, title: '第二十三讲 违法所得的没收程序（320题-324题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=26' },
          { idx: 27, title: '第二十四讲 精神病人的强制医疗程序（325题-335题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=27' },
          { idx: 28, title: '第二十五讲 涉外刑事诉讼程序与司法协助制（336题-338题）', link: 'https://www.bilibili.com/video/BV1eDXzBKEZ6?p=28' }
        ]
      }
    }
  },
  '民诉法': {
    phases: {
      '专题强化': {
        teacher: '刘鹏飞',
        bvid: 'BV16MiQBvEuE',
        status: 'complete',
        episodes: [
          { idx: 1, title: '专题一 基本理论', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=1' },
          { idx: 2, title: '专题二 基本原则', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=2' },
          { idx: 3, title: '专题三 基本制度', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=3' },
          { idx: 4, title: '专题四 原告与被告', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=4' },
          { idx: 5, title: '专题五 共同诉讼人', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=5' },
          { idx: 6, title: '专题六 诉讼代表人', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=6' },
          { idx: 7, title: '专题七 诉讼第三人', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=7' },
          { idx: 8, title: '专题八 诉讼代理人', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=8' },
          { idx: 9, title: '专题九 级别管辖', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=9' },
          { idx: 10, title: '专题十 地域管辖', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=10' },
          { idx: 11, title: '专题十一 裁定管辖和管辖权恒定', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=11' },
          { idx: 12, title: '专题十二 证明对象', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=12' },
          { idx: 13, title: '专题十三 举证责任', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=13' },
          { idx: 14, title: '专题十四 证据的学理分类', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=14' },
          { idx: 15, title: '专题十五 证据的法定种类', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=15' },
          { idx: 16, title: '专题十六 保全', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=16' },
          { idx: 17, title: '专题十七 先予执行', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=17' },
          { idx: 18, title: '专题十八 强制措施', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=18' },
          { idx: 19, title: '专题十九 期间与送达', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=19' },
          { idx: 20, title: '专题二十 调解的适用', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=20' },
          { idx: 21, title: '专题二十一 调解协议与调解书', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=21' },
          { idx: 22, title: '专题二十二 起诉与受理', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=22' },
          { idx: 23, title: '专题二十三 审理前的准备', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=23' },
          { idx: 24, title: '专题二十四 庭审程序', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=24' },
          { idx: 25, title: '专题二十五 诉讼中的特殊情形', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=25' },
          { idx: 26, title: '专题二十六 简易程序一般规定', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=26' },
          { idx: 27, title: '专题二十七 小额诉讼程序', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=27' },
          { idx: 28, title: '专题二十八 上诉', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=28' },
          { idx: 29, title: '专题二十九 二审的审理', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=29' },
          { idx: 30, title: '专题三十 二审的裁判', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=30' },
          { idx: 31, title: '专题三十一 再审程序的启动', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=31' },
          { idx: 32, title: '专题三十二 再审程序的审理', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=32' },
          { idx: 33, title: '专题三十三 再审程序的裁判与调解', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=33' },
          { idx: 34, title: '专题三十四 第三人撤销之诉的基本制度', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=34' },
          { idx: 35, title: '专题三十五 执行前对案外人的救济', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=35' },
          { idx: 36, title: '专题三十六 反诉', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=36' },
          { idx: 37, title: '专题三十七 “增变反”在诉讼程序中的具体处理', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=37' },
          { idx: 38, title: '专题三十八 公益诉讼的起诉条件', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=38' },
          { idx: 39, title: '专题三十九 公益诉讼的程序规定', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=39' },
          { idx: 40, title: '专题四十 特别程序', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=40' },
          { idx: 41, title: '专题四十一 督促程序', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=41' },
          { idx: 42, title: '专题四十二 公示催告程序', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=42' },
          { idx: 43, title: '专题四十三 在线诉讼', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=43' },
          { idx: 44, title: '专题四十四 执行开始', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=44' },
          { idx: 45, title: '专题四十五 执行阻却', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=45' },
          { idx: 46, title: '专题四十六 执行救济', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=46' },
          { idx: 47, title: '专题四十七 执行措施', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=47' },
          { idx: 48, title: '专题四十八 仲裁协议的效力', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=48' },
          { idx: 49, title: '专题四十九 仲裁程序', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=49' },
          { idx: 50, title: '专题五十 撤销仲裁裁决与不予执行仲裁裁决', link: 'https://www.bilibili.com/video/BV16MiQBvEuE?p=50' }
        ]
      },
      '真题破译': {
        teacher: '已完结',
        bvid: 'BV1XW97BMEMQ',
        status: 'complete',
        episodes: [
          { idx: 1, title: '第一讲 基本理论、原则和制度（1题-20题）', link: 'https://www.bilibili.com/video/BV1XW97BMEMQ?p=1' },
          { idx: 2, title: '第二讲 当事人和代理人（21题-56题）', link: 'https://www.bilibili.com/video/BV1XW97BMEMQ?p=2' },
          { idx: 3, title: '第三节 管辖（57题-84题）', link: 'https://www.bilibili.com/video/BV1XW97BMEMQ?p=3' },
          { idx: 4, title: '第四讲 证据与证明（85题-118题）', link: 'https://www.bilibili.com/video/BV1XW97BMEMQ?p=4' },
          { idx: 5, title: '第五讲 诉讼保障制度（119题-135题）', link: 'https://www.bilibili.com/video/BV1XW97BMEMQ?p=5' },
          { idx: 6, title: '第六讲 诉讼调解与和解（136题-141题）', link: 'https://www.bilibili.com/video/BV1XW97BMEMQ?p=6' },
          { idx: 7, title: '第七讲 一审普通程序（142题-174题）', link: 'https://www.bilibili.com/video/BV1XW97BMEMQ?p=7' },
          { idx: 8, title: '第八讲 一审简易程序（175题-181题）', link: 'https://www.bilibili.com/video/BV1XW97BMEMQ?p=8' },
          { idx: 9, title: '第九讲 二审程序（182题-208题）', link: 'https://www.bilibili.com/video/BV1XW97BMEMQ?p=9' },
          { idx: 10, title: '第十讲 审判监督程序（209题-219题）', link: 'https://www.bilibili.com/video/BV1XW97BMEMQ?p=10' },
          { idx: 11, title: '第十一讲 第三人撤销之诉（220题-224题）', link: 'https://www.bilibili.com/video/BV1XW97BMEMQ?p=11' },
          { idx: 12, title: '第十二讲 增加、变更诉讼请求和反诉（225题-234题）', link: 'https://www.bilibili.com/video/BV1XW97BMEMQ?p=12' },
          { idx: 13, title: '第十三讲 公益诉讼（235题-243题）', link: 'https://www.bilibili.com/video/BV1XW97BMEMQ?p=13' },
          { idx: 14, title: '第十四讲 特别、督促与公示催告程序（244题-269题）', link: 'https://www.bilibili.com/video/BV1XW97BMEMQ?p=14' },
          { idx: 15, title: '第十五讲 在线诉讼（270题-273题）', link: 'https://www.bilibili.com/video/BV1XW97BMEMQ?p=15' },
          { idx: 16, title: '第十六讲 民事执行程序（274题-309题）', link: 'https://www.bilibili.com/video/BV1XW97BMEMQ?p=16' },
          { idx: 17, title: '第十七讲 仲裁法（310题-340题）', link: 'https://www.bilibili.com/video/BV1XW97BMEMQ?p=17' }
        ]
      }
    }
  },
  '理论法': {
    phases: {
      '专题强化': {
        teacher: '白斌',
        bvid: 'BV1PmfXBMEpw',
        status: 'complete',
        episodes: [
          { idx: 1, title: '专题1 法的概念', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=1' },
          { idx: 2, title: '专题2 法的本质与特征', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=2' },
          { idx: 3, title: '专题3 法的作用与价值', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=3' },
          { idx: 4, title: '专题4 法的要素', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=4' },
          { idx: 5, title: '专题5 法的渊源', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=5' },
          { idx: 6, title: '专题6 法律部门与法律体系', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=6' },
          { idx: 7, title: '专题7 法的效力', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=7' },
          { idx: 8, title: '专题8 法的关系', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=8' },
          { idx: 9, title: '专题9 法律责任', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=9' },
          { idx: 10, title: '第二讲 法的运行 专题10 立法', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=10' },
          { idx: 11, title: '专题11 法的实施', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=11' },
          { idx: 12, title: '专题12 法适用的一般原理', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=12' },
          { idx: 13, title: '专题14 法律漏洞的填补', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=13' },
          { idx: 14, title: '专题15_16 第三讲：法与社会 法与社会的一般理论 法与经济、科技、政治和宗教的关系', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=14' },
          { idx: 15, title: '第四讲 法的演进 专题17 法的起源', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=15' },
          { idx: 16, title: '专题19 法的传统', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=16' },
          { idx: 17, title: '专题20 习近平法治思想的形成发展', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=17' },
          { idx: 18, title: '专题21 习近平法治思想的重大意义', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=18' },
          { idx: 19, title: '第六讲 专题22、专题23、专题24 坚持中国特色社会主义法治道路', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=19' },
          { idx: 20, title: '专题25 坚持依宪治国依宪执政', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=20' },
          { idx: 21, title: '专题26 坚持在法治轨道上推进国家治理体系和治理能力现代化', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=21' },
          { idx: 22, title: '专题27 坚持建设中国特色社会主义法治体系', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=22' },
          { idx: 23, title: '专题28 坚持依法治国、 依法执政、 依法行政共同推进，法治国家、 法治政府、 法治社会一体建设', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=23' },
          { idx: 24, title: '专题29 坚持全面推进科学立法、 严格执法、 公正司法、 全民守法', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=24' },
          { idx: 25, title: '专题30 坚持统筹推进国内法治和涉外法治', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=25' },
          { idx: 26, title: '专题31 建设德才兼备的高素质法治工作队伍', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=26' },
          { idx: 27, title: '专题32 坚持抓住领导干部这个“关键少数”', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=27' },
          { idx: 28, title: '第七讲 习近平法治思想的实践要求 专题33 习近平法治思想的实践要求', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=28' },
          { idx: 29, title: '第八讲宪法的基本理论 专题34 宪法的概念', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=29' },
          { idx: 30, title: '专题35 宪法的历史发展（上）', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=30' },
          { idx: 31, title: '专题35 宪法的历史发展（下）', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=31' },
          { idx: 32, title: '专题36 宪法的基本原则', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=32' },
          { idx: 33, title: '专题37 宪法的渊源与宪法典的结构', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=33' },
          { idx: 34, title: '专题38 宪法的作用、宪法规范与宪法效力', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=34' },
          { idx: 35, title: '第九讲 宪法的实施及其保障 专题39 宪法实施概述', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=35' },
          { idx: 36, title: '专题40 宪法的修改和解释', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=36' },
          { idx: 37, title: '专题41 宪法监督pc', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=37' },
          { idx: 38, title: '专题44 选举制度', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=38' },
          { idx: 39, title: '专题45 国家结构形式', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=39' },
          { idx: 40, title: '专题46 民族区域自治制度', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=40' },
          { idx: 41, title: '专题47 特别行政区制度（上）', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=41' },
          { idx: 42, title: '专题48 基层群众性自治组织', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=42' },
          { idx: 43, title: '专题49 公民的基本权利与义务概述', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=43' },
          { idx: 44, title: '专题50 我国公民的基本权利', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=44' },
          { idx: 45, title: '专题51 国家机构概述', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=45' },
          { idx: 46, title: '专题52 全国人民代表大会及其常务委员会（上）', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=46' },
          { idx: 47, title: '专题52 全国人民代表大会及其常务委员会（下）', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=47' },
          { idx: 48, title: '专题54 国务院', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=48' },
          { idx: 49, title: '专题55 中央军事委员会', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=49' },
          { idx: 50, title: '专题56 地方各级人民代表大会和地方各级人民政府', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=50' },
          { idx: 51, title: '专题57 人民法院与人民检察院', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=51' },
          { idx: 52, title: '专题58 监察委员会', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=52' },
          { idx: 53, title: '专题59 国家象征', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=53' },
          { idx: 54, title: '第十五讲司法制度和法律职业道德概述 专题60一般规定', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=54' },
          { idx: 55, title: '第十六讲审判制度和法官职业道德 专题61审判制度概述', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=55' },
          { idx: 56, title: '专题62 法官职业道德', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=56' },
          { idx: 57, title: '专题63 法官职业责任', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=57' },
          { idx: 58, title: '第十七讲检察制度和检察官职业道德 专题64检察制度概述', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=58' },
          { idx: 59, title: '专题65 检察官', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=59' },
          { idx: 60, title: '专题66检察官职业道德 专题67检察官职业责任', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=60' },
          { idx: 61, title: '第十八讲律师制度和律师职业道德 专题68律师制度概述', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=61' },
          { idx: 62, title: '专题69 律师', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=62' },
          { idx: 63, title: '专题70 律师事务所', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=63' },
          { idx: 64, title: '专题71 律师职业道德与职业责任', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=64' },
          { idx: 65, title: '专题72 法律援助法', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=65' },
          { idx: 66, title: '第十九讲公证制度和公证员职业道德 专题73公证制度概述', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=66' },
          { idx: 67, title: '专题74 公证机构与公证员', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=67' },
          { idx: 68, title: '专题75 公证程序与公证效力', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=68' },
          { idx: 69, title: '专题76 公证员职业道德与职业责任', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=69' },
          { idx: 70, title: '第二十讲其他法律职业人员职业道德 专题77其他法律职业人员职业道德', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=70' },
          { idx: 71, title: '第二十一讲先秦时期的法律思想与制度 专题78先秦时期的法律思想与制度', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=71' },
          { idx: 72, title: '第二十二讲秦汉至魏晋南北朝时期的法律思想与制度 专题79秦汉时期的法律思想与制度', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=72' },
          { idx: 73, title: '专题80 魏晋南北朝时期的法律思想与制度', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=73' },
          { idx: 74, title: '第二十三讲隋唐宋元时期的法律思想与制度 专题81隋《开皇律》', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=74' },
          { idx: 75, title: '专题82 唐律与中华法系', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=75' },
          { idx: 76, title: '专题83两宋的法律思想与制度 专题84元代的四等人', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=76' },
          { idx: 77, title: '专题85 明代的法律思想与制度', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=77' },
          { idx: 78, title: '专题86 清代的法律思想与制度（近代以前）', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=78' },
          { idx: 79, title: '第二十四讲 专题87清末的法律思想与制度', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=79' },
          { idx: 80, title: '第二十五讲中华民国的法律思想与制度 专题88民国初期的法律思想', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=80' },
          { idx: 81, title: '专题89 中华民国的法律制度', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=81' },
          { idx: 82, title: '第二十六讲中国共产党民主政权宪法性文件 专题90中国共产党民主政权宪法性文件与审判制度', link: 'https://www.bilibili.com/video/BV1PmfXBMEpw?p=82' }
        ]
      },
      '真题破译': {
        teacher: '更新中',
        bvid: 'BV1CKQ8BHE1A',
        status: 'complete',
        episodes: [
          { idx: 1, title: '第一讲 法的本体 （1题-64题）', link: 'https://www.bilibili.com/video/BV1CKQ8BHE1A?p=1' },
          { idx: 2, title: '第二讲 法的运行（65题-106题）', link: 'https://www.bilibili.com/video/BV1CKQ8BHE1A?p=2' },
          { idx: 3, title: '第三讲 法与社会（107题-116题）', link: 'https://www.bilibili.com/video/BV1CKQ8BHE1A?p=3' },
          { idx: 4, title: '第四讲 法的演进（117题-126题）', link: 'https://www.bilibili.com/video/BV1CKQ8BHE1A?p=4' },
          { idx: 5, title: '第五讲 习近平法治思想的重大意义（127题-140题）', link: 'https://www.bilibili.com/video/BV1CKQ8BHE1A?p=5' },
          { idx: 6, title: '第六讲 习近平法治思想的核心要义 （141题-169题）', link: 'https://www.bilibili.com/video/BV1CKQ8BHE1A?p=6' },
          { idx: 7, title: '第七讲 习近平法治思想的实践要求（170题-176题）', link: 'https://www.bilibili.com/video/BV1CKQ8BHE1A?p=7' }
        ]
      }
    }
  },
  '商经法': {
    phases: {
      '专题强化': {
        teacher: '郄鹏恩',
        bvid: 'BV1XckvBoEQy',
        status: 'complete',
        episodes: [
          { idx: 1, title: '序言', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=1' },
          { idx: 2, title: '专题一 公司法总则（上）', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=2' },
          { idx: 3, title: '专题一 公司法总则（下）', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=3' },
          { idx: 4, title: '专题二 公司的设立和公司的登记', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=4' },
          { idx: 5, title: '专题三 股东的出资', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=5' },
          { idx: 6, title: '专题四 股东资格，股东的权力和义务', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=6' },
          { idx: 7, title: '专题五 有限责任公司的股权转让（上）', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=7' },
          { idx: 8, title: '专题五 有限责任公司的股民转让（下）', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=8' },
          { idx: 9, title: '专题六 股份有限公司的股份发行与转让', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=9' },
          { idx: 10, title: '专题七 公司的组织机构（上）', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=10' },
          { idx: 11, title: '专题七 公司的组织机构（下）', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=11' },
          { idx: 12, title: '专题八 国家出资公司组织的特别规定', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=12' },
          { idx: 13, title: '专题九 公司董事，监事，高级管理人员的资格和义务', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=13' },
          { idx: 14, title: '专题十 公司财务会计，合并与分立，增资与减资，解散与清算（上）', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=14' },
          { idx: 15, title: '专题十 公司财务会计，合并与分立，增资与减资，解散与清算（下）', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=15' },
          { idx: 16, title: '专题11 合伙企业的设立、财产、事务执行', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=16' },
          { idx: 17, title: '专题12 合伙企业与第三人的关系、入伙和退伙、合伙人之间的转换', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=17' },
          { idx: 18, title: '专题13 民营经济促进法、个人独资企业法、外商投资法', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=18' },
          { idx: 19, title: '专题14 破产法总论（上）', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=19' },
          { idx: 20, title: '专题15 破产法总论（下）', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=20' },
          { idx: 21, title: '专题16 破产法分论——重整、和解、破产清算程序', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=21' },
          { idx: 22, title: '专题17 票据原理', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=22' },
          { idx: 23, title: '专题18 票据行为（汇票）', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=23' },
          { idx: 24, title: '专题19 本票与支票', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=24' },
          { idx: 25, title: '专题20 保险法概述', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=25' },
          { idx: 26, title: '专题21 人身保险（上）', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=26' },
          { idx: 27, title: '专题21 人身保险（下）', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=27' },
          { idx: 28, title: '专题22 财产保险合同', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=28' },
          { idx: 29, title: '专题23 证券业法律制度', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=29' },
          { idx: 30, title: '专题24 信托法律制度', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=30' },
          { idx: 31, title: '专题25 著作权概述', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=31' },
          { idx: 32, title: '专题26 著作权的内容与侵权行为（上）', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=32' },
          { idx: 33, title: '专题26 著作权的内容与侵权行为（下）', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=33' },
          { idx: 34, title: '专题27 邻接权', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=34' },
          { idx: 35, title: '专题28 专利法概述', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=35' },
          { idx: 36, title: '专题29 专利侵权行为', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=36' },
          { idx: 37, title: '专题30 注册商标概述', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=37' },
          { idx: 38, title: '专题31 商标权的消灭和商标侵权行为', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=38' },
          { idx: 39, title: '专题32 劳动法概述、劳动基准法', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=39' },
          { idx: 40, title: '专题33  劳动合同法', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=40' },
          { idx: 41, title: '专题34 劳动争议的认定和处理', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=41' },
          { idx: 42, title: '专题35 社会保险与军人保险法律关系', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=42' },
          { idx: 43, title: '专题36 反垄断法', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=43' },
          { idx: 44, title: '专题37 反不正当竞争法', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=44' },
          { idx: 45, title: '专题38 消费者权益保护法', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=45' },
          { idx: 46, title: '专题39 产品质量法和食品安全法', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=46' },
          { idx: 47, title: '专题40 商业银行与银行业监督管理', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=47' },
          { idx: 48, title: '专题41 税收征纳实体法', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=48' },
          { idx: 49, title: '专题42 税收征收管理法律制度', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=49' },
          { idx: 50, title: '专题43 审计法', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=50' },
          { idx: 51, title: '专题44 土地权属法律制度', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=51' },
          { idx: 52, title: '专题45 城市房地产管理法、城乡规划法、不动产登记暂行条例', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=52' },
          { idx: 53, title: '专题46 环境影响评价、环境保护法律制度', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=53' },
          { idx: 54, title: '专题47 森林和矿产资源法律制度', link: 'https://www.bilibili.com/video/BV1XckvBoEQy?p=54' }
        ]
      },
      '真题破译': {
        teacher: '更新中',
        bvid: 'BV1HFdDBDE4q',
        status: 'complete',
        episodes: [
          { idx: 1, title: '第一讲 公司法上（1题-21题）', link: 'https://www.bilibili.com/video/BV1HFdDBDE4q?p=1' },
          { idx: 2, title: '第一讲 公司法中（22题-42题）', link: 'https://www.bilibili.com/video/BV1HFdDBDE4q?p=2' },
          { idx: 3, title: '第一讲 公司法下（43题-62题）', link: 'https://www.bilibili.com/video/BV1HFdDBDE4q?p=3' },
          { idx: 4, title: '第二讲 合伙企业法（63题-86题）', link: 'https://www.bilibili.com/video/BV1HFdDBDE4q?p=4' },
          { idx: 5, title: '第三讲 个人独资企业法与外商投资法（87题-89题）', link: 'https://www.bilibili.com/video/BV1HFdDBDE4q?p=5' }
        ]
      }
    }
  },
  '行政法': {
    phases: {
      '专题强化': {
        teacher: '魏建新',
        bvid: 'BV1HnrPBSExE',
        status: 'complete',
        episodes: [
          { idx: 1, title: '前言', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=1' },
          { idx: 2, title: '专题1 行政与行政法', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=2' },
          { idx: 3, title: '专题2 行政法基本原则', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=3' },
          { idx: 4, title: '专题3 中央行政机关', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=4' },
          { idx: 5, title: '专题4 地方行政机关与实施行政职能的非政府组织', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=5' },
          { idx: 6, title: '专题5 公务员概述与公务员录用', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=6' },
          { idx: 7, title: '专题6 公务员职位管理', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=7' },
          { idx: 8, title: '专题7 公务员的处分与救济', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=8' },
          { idx: 9, title: '专题8 抽象行政行为概述', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=9' },
          { idx: 10, title: '专题9 行政立法的程序与监督', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=10' },
          { idx: 11, title: '专题10 具体行政行为概述', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=11' },
          { idx: 12, title: '专题11 具体行政行为的效力与合法', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=12' },
          { idx: 13, title: '专题12 行政许可概述', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=13' },
          { idx: 14, title: '专题13 行政许可实施主体和程序', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=14' },
          { idx: 15, title: '专题14 行政许可的费用和监督管理', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=15' },
          { idx: 16, title: '专题15 行政处罚概述', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=16' },
          { idx: 17, title: '专题16 行政处罚的实施主体、管辖与适用', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=17' },
          { idx: 18, title: '专题17 行政处罚的程序', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=18' },
          { idx: 19, title: '专题18 行政强制概述', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=19' },
          { idx: 20, title: '专题19 行政强制措施实施的主体与程序', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=20' },
          { idx: 21, title: '专题20 行政强制执行的主体与程序', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=21' },
          { idx: 22, title: '专题21 治安管理处罚概述、实施主体与适用', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=22' },
          { idx: 23, title: '专题22 治安管理处罚的程序', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=23' },
          { idx: 24, title: '专题23 政府信息公开的意义、范围 与主体', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=24' },
          { idx: 25, title: '专题24 政府信息公开的程序', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=25' },
          { idx: 26, title: '专题25 行政复议的范围与主体', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=26' },
          { idx: 27, title: '专题26 行政复议的申请与受理', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=27' },
          { idx: 28, title: '专题27 行政复议的审理', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=28' },
          { idx: 29, title: '专题28 行政复议的决定与执行', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=29' },
          { idx: 30, title: '专题29 行政诉讼受理的案件', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=30' },
          { idx: 31, title: '专题30 行政诉讼不予受理的案件', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=31' },
          { idx: 32, title: '专题31 其他司法解释中的行政诉讼的受案范围', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=32' },
          { idx: 33, title: '专题32 行政诉讼的原告', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=33' },
          { idx: 34, title: '专题33 行政诉讼的被告', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=34' },
          { idx: 35, title: '专题34 行政诉讼的第三人和共同诉讼人', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=35' },
          { idx: 36, title: '专题35 行政诉讼的级别管辖', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=36' },
          { idx: 37, title: '专题36 行政诉讼的地域管辖', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=37' },
          { idx: 38, title: '专题37 起诉与受理', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=38' },
          { idx: 39, title: '专题38 行政诉讼的第一审程序、第二审程序', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=39' },
          { idx: 40, title: '专题39  行政案件审理中的特殊制度', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=40' },
          { idx: 41, title: '专题40 行政诉讼的特殊形式', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=41' },
          { idx: 42, title: '专题41 行政诉讼的证据种类与举证', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=42' },
          { idx: 43, title: '专题42 行政诉讼的证据调取与认定、法律适用', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=43' },
          { idx: 44, title: '专题43 行政诉讼的第一审判决', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=44' },
          { idx: 45, title: '专题44 行政诉讼的规范性文件附带审查和裁判执行', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=45' },
          { idx: 46, title: '专题45 国家赔偿概述', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=46' },
          { idx: 47, title: '专题46 行政赔偿', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=47' },
          { idx: 48, title: '专题47 司法赔偿', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=48' },
          { idx: 49, title: '专题48 国家赔偿方式、标准与费用', link: 'https://www.bilibili.com/video/BV1HnrPBSExE?p=49' }
        ]
      },
      '真题破译': {
        teacher: '更新中',
        bvid: '',
        status: 'pending',
        episodes: []
      }
    }
  },
  '三国法': {
    phases: {
      '专题强化': {
        teacher: '殷敏',
        bvid: 'BV1j7vsBDEWu',
        status: 'complete',
        episodes: [
          { idx: 1, title: '导论', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=1' },
          { idx: 2, title: '专题1_国际法的渊源', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=2' },
          { idx: 3, title: '专题2_国际法的基本原则', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=3' },
          { idx: 4, title: '专题3 国际法在国内的适用', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=4' },
          { idx: 5, title: '专题4_条约法律制度（上）', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=5' },
          { idx: 6, title: '专题4_条约法律制度（下）', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=6' },
          { idx: 7, title: '专题5_国家', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=7' },
          { idx: 8, title: '专题6_联合国', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=8' },
          { idx: 9, title: '专题7_国际争法律责任', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=9' },
          { idx: 10, title: '专题8_领土', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=10' },
          { idx: 11, title: '专题9_海洋法', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=11' },
          { idx: 12, title: '专题10_国际法上的特殊空间', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=12' },
          { idx: 13, title: '专题11_国际环保法', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=13' },
          { idx: 14, title: '专题12_中国国籍制度', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=14' },
          { idx: 15, title: '专题13_中国《出境入境管理法》', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=15' },
          { idx: 16, title: '专题14_外交保护', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=16' },
          { idx: 17, title: '专题15_引渡与庇护', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=17' },
          { idx: 18, title: '专题16_外交机关与使领馆人员', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=18' },
          { idx: 19, title: '专题17_外交特权与豁免以及领事特权与豁免', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=19' },
          { idx: 20, title: '专题18_国际争端的解决方式', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=20' },
          { idx: 21, title: '专题19_国际争端的法律解决方法', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=21' },
          { idx: 22, title: '专题20_战争的法律后果', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=22' },
          { idx: 23, title: '专题21_对作战的限制和对受难者的保护', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=23' },
          { idx: 24, title: '专题22_国际刑事法院', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=24' },
          { idx: 25, title: '专题23_国际私法的基本概念', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=25' },
          { idx: 26, title: '专题24_国际私法的基本制度', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=26' },
          { idx: 27, title: '专题25_一般原则和经常居所地pc', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=27' },
          { idx: 28, title: '专题26_权利能力和行为能力的法律适用', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=28' },
          { idx: 29, title: '专题27_代理、_信托、_时效和仲裁协议的法律适用', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=29' },
          { idx: 30, title: '专题28_物权的法律适用', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=30' },
          { idx: 31, title: '专题29_债权的法律适用', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=31' },
          { idx: 32, title: '专题30_知识产权的法律适用', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=32' },
          { idx: 33, title: '专题31_商事关系的法律适用', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=33' },
          { idx: 34, title: '专题32_婚姻、_家庭_(收养、_监护、_扶养)_、_继承的法律适用', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=34' },
          { idx: 35, title: '专题33_国际商事仲裁', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=35' },
          { idx: 36, title: '专题34_我国关于国际民事案件的管辖权规定', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=36' },
          { idx: 37, title: '专题35_域外送达与域外取证', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=37' },
          { idx: 38, title: '专题36_外国法院判决的承认和执行', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=38' },
          { idx: 39, title: '专题37_区际文书送达与区际调取证据', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=39' },
          { idx: 40, title: '专题38_区际判决与区际仲裁裁决的认可和执行', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=40' },
          { idx: 41, title: '专题39_国际货物买卖法律制度之国际贸易术语', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=41' },
          { idx: 42, title: '专题40_国际货物买卖法律制度之1980年《联合国国际货物销售合同公约》', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=42' },
          { idx: 43, title: '专题41_国际海上货物运输法律制度之提单法律基础知识', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=43' },
          { idx: 44, title: '专题42_国际海上货物运输法律制度之提单重要国际公约及中国_《海商法》', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=44' },
          { idx: 45, title: '专题43_国际货物运输保险法律制度之确立险别的两个依据', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=45' },
          { idx: 46, title: '专题44_国际货物运输保险法律制度之险别', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=46' },
          { idx: 47, title: '专题45_国际贸易支付法律制度之托收法律关系', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=47' },
          { idx: 48, title: '专题46_国际贸易支付法律制度之银行信用证', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=48' },
          { idx: 49, title: '专题47_中国_《对外贸易法》', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=49' },
          { idx: 50, title: '专题48_《出口管制法》', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=50' },
          { idx: 51, title: '专题49_贸易救济措施之反倾销措施', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=51' },
          { idx: 52, title: '专题50_贸易救济措施之反补贴措施', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=52' },
          { idx: 53, title: '专题51_贸易救济措施之保障措施', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=53' },
          { idx: 54, title: '专题52_世界贸易组织基本法律制度', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=54' },
          { idx: 55, title: '专题53_《服务贸易总协定》_(ＧＡＴＳ)', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=55' },
          { idx: 56, title: '专题54_WTO争端解决机制', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=56' },
          { idx: 57, title: '专题55_《巴黎公约》', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=57' },
          { idx: 58, title: '专题56_《伯尔尼公约》', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=58' },
          { idx: 59, title: '专题57_《与贸易有关的知识产权协议》(TRIPS)', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=59' },
          { idx: 60, title: '专题58_技术转让法', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=60' },
          { idx: 61, title: '专题59_《与贸易有关的投资措施协议》(TRIMS)', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=61' },
          { idx: 62, title: '专题60_《多边投资担保机构公约》（MIGA）和《关于解决国家和他国国民之间投资争端公约》（ICSID)', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=62' },
          { idx: 63, title: '专题61_国际贷款协议的种类及国际融资担保', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=63' },
          { idx: 64, title: '专题62_居民税收管辖权与来源地税收管辖权', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=64' },
          { idx: 65, title: '专题63_国际双重征税及其解决', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=65' },
          { idx: 66, title: '专题64_国际逃税、_避税及其防止', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=66' },
          { idx: 67, title: '专题65_海商法', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=67' },
          { idx: 68, title: '专题66_国际经济法新领域', link: 'https://www.bilibili.com/video/BV1j7vsBDEWu?p=68' }
        ]
      },
      '真题破译': {
        teacher: '已完结',
        bvid: 'BV16nDjB6ELM',
        status: 'complete',
        episodes: [
          { idx: 1, title: '第一讲 国际法导论（1题-5题）', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=1' },
          { idx: 2, title: '第二讲 条约法（6题-12题）', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=2' },
          { idx: 3, title: '第三讲 国际法律责任（13题-25题）', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=3' },
          { idx: 4, title: '第四讲 国际法上的空间划分（26题-41题）', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=4' },
          { idx: 5, title: '第五讲 国际法上的个人（42题-58题）', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=5' },
          { idx: 6, title: '第六讲 外交关系与领事关系法（59题-68题）', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=6' },
          { idx: 7, title: '第七讲 国际争端解决（69题-79题）', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=7' },
          { idx: 8, title: '第八讲 战争与武装冲突法（80题-86题）', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=8' },
          { idx: 9, title: '第九讲 国际私法的基本理论（87题-97题）', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=9' },
          { idx: 10, title: '第十讲（上）涉外民商事关系法律适用（98题-125题）', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=10' },
          { idx: 11, title: '第十讲（下） 涉外民商事关系法律适用（126题-155题）', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=11' },
          { idx: 12, title: '第十一讲  国际民商事争议的解决 （156题-179题）', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=12' },
          { idx: 13, title: '第十二讲 区际司法协助  (180题-190题)', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=13' },
          { idx: 14, title: '第十三讲(上)  国际贸易私法 (191题-211题)', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=14' },
          { idx: 15, title: '第十三讲(下)  国际贸易私法 (212题-235题)', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=15' },
          { idx: 16, title: '第十四讲 国际贸易公法 (236题-265题)', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=16' },
          { idx: 17, title: '第十五讲 国际知识产权法(266题-273题)', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=17' },
          { idx: 18, title: '第十六讲 国际投资法(274题-280题)', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=18' },
          { idx: 19, title: '第十七讲 国际融资法和国际税法  (281题-294题)', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=19' },
          { idx: 20, title: '第十八讲 海商法 (295题-300题）', link: 'https://www.bilibili.com/video/BV16nDjB6ELM?p=20' }
        ]
      }
    }
  },
};